# Taps
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "jesseduffield/lazygit"
tap "keith/formulae/reminders-cli"
tap "yakitrak/yakitrak"

# CLI Utilities
brew "wget"
brew "fzf"
brew "git"
brew "ripgrep"
brew "jq"
brew "gnu-sed"
brew "tmux"
brew "taskwarrior-tui"
brew "task"
brew "socat"
brew "netcat"
brew "socat"
brew "hping"
brew "name-that-hash"
brew "spoof-mmac"

# Development Tools
brew "python"
brew "pyenv"
brew "pyenv-virtualenv"
brew "go"
brew "node"
brew "rust"
brew "ruby"
brew "pipx"

# Editors & Shell Enhancements
brew "neovim"
brew "powerlevel10k"

# Kubernetes & Cloud
brew "helm"
brew "kubernetes-cli"
brew "k9s"
brew "terraform"
brew "azure-cli"
brew "aws"
brew "ansible"

# Networking & Security Tools
brew "nmap"
brew "tcptraceroute"
brew "telnet"
brew "ipcalc"
brew "bettercap"
brew "gobuster"

# System Monitoring
brew "htop"
brew "btop"
brew "neofetch"

# Database & Caching
brew "postgresql"
brew "redis"

# Containerization
brew "docker"
brew "docker-compose"
brew "gitlab-runner"

# Productivity & Misc
brew "yakitrak/yakitrak/obsidian-cli"
brew "keith/formulae/reminders-cli"
brew "spotifyd"
brew "spotify_player"
brew "nchat"

# Casks
cask "obsidian"
cask "spotify"
cask "alacritty"
cask "shortcat"
cask "raycast"
cask "discord"
cask "postman"
cask "karabiner-elements"
cask "rectangle"
cask "keepassxc"

# Fonts
cask "font-hack-nerd-font"
cask "font-jetbrains-mono-nerd-font"
