[env]
# TERM variable
#
# This value is used to set the `$TERM` environment variable for
# each instance of Alacritty. If it is not present, alacritty will
# check the local terminfo database and use `alacritty` if it is
# available, otherwise `xterm-256color` is used.
# You can check the TERM variable with echo $TERM outside of tmux
# https://copyprogramming.com/howto/why-would-i-set-term-to-xterm-256color-when-using-alacritty
TERM = "alacritty"
# TERM = "xterm-256color"
# TERM: screen-256color

[terminal]

  [terminal.shell]
  program = "/bin/zsh"
  args = ["--login", "-c", "/opt/homebrew/bin/tmux attach || /opt/homebrew/bin/tmux"]

[window]
decorations = "Buttonless"
opacity = 0.85
# blur = true
# padding = { x = 2, y = 2}
dynamic_padding = true

[font]
normal = {family = "JetBrainsMono Nerd Font", style = "Regular"}
size = 12

