refix
unbind C-b
set -g prefix C-w
bind C-w send-prefix

# General Options
set -g base-index 1
set -g pane-base-index 1
set -g escape-time 0
set -g history-limit 50000
set -g mouse on

# Reload Config
bind R source-file ~/.config/psmux/psmux.conf \; display "Reloaded!"

# Pane Management & Navigation
bind | split-window -v
bind \ split-window -h

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Resizing
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

bind -r Left resize-pane -L 5
bind -r Right resize-pane -R 5
bind -r Up resize-pane -U 5
bind -r Down resize-pane -R 5

# Copy Mode
bind Enter copy-mode

# Lazygit Popup
bind g display-popup -w 80% -h 80% lazygit
